--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DO MEDICO ---
CREATE VIEW VerMedicos 
AS 
SELECT MED.NOME,US.EMAIL ,TIP.NOME AS 'PRIVILEGIOS',MED.CRM,CLI.NOME_FANTASIA AS 'Clinica'
FROM Medico AS MED
INNER JOIN Usuario AS US ON MED.ID_USUARIO = US.ID
INNER JOIN Tipo_Usuario AS TIP ON US.ID_TIPO_USUARIO = TIP.ID
INNER JOIN Clinica AS CLI ON MED.ID_CLINICA = CLI.ID;

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DO PACIENTE ---
CREATE VIEW VerPacientes
AS
SELECT PAC.NOME,US.EMAIL,TIP.NOME AS 'PRIVILEGIOS', PAC.CPF, PAC.RG , PAC.TELEFONE , PAC.DATA_NASCIMENTO
FROM Paciente AS PAC
INNER JOIN Usuario AS US ON PAC.ID_USUARIO = US.ID
INNER JOIN Tipo_Usuario AS TIP ON US.ID_TIPO_USUARIO = TIP.ID;

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DA CLINICA ---
CREATE VIEW VerClinicas
AS
SELECT CLI.NOME_FANTASIA , CLI.ENDERECO , CLI.NUMERO , CLI.CEP
FROM Clinica AS CLI;

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DA CONSULTA
CREATE VIEW VerConsultas
AS
SELECT MED.NOME AS 'DOUTOR' , PAC.NOME AS 'PACIENTE' , CLI.NOME_FANTASIA AS 'CLINICA' , CLI.ENDERECO ,  ESP.NOME AS 'ESPECIALIDADE' , CON.DATA_CONSULTA 'DATA'
FROM Consulta AS CON
INNER JOIN Medico AS MED ON CON.ID_MEDICO = MED.ID
INNER JOIN Especialidade AS ESP ON MED.ID_ESPECIALIDADE = ESP.ID
INNER JOIN Paciente AS PAC ON CON.ID_PACIENTE = PAC.ID
INNER JOIN Clinica AS CLI ON MED.ID_CLINICA = CLI.ID;
