--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DO MEDICO ---
CREATE VIEW VerMedicos 
AS 
SELECT MED.NOME,US.EMAIL,TIP.NOME AS 'Privilegios',MED.CRM,CLI.NOME_FANTASIA AS 'Clinica'
FROM Medico AS MED
INNER JOIN Usuario AS US ON MED.ID_USUARIO = US.ID
INNER JOIN Tipo_Usuario AS TIP ON US.ID_TIPO_USUARIO = TIP.ID
INNER JOIN Clinica AS CLI ON MED.ID_CLINICA = CLI.ID;

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DO PACIENTE ---
CREATE VIEW VerPacientes
AS
SELECT PAC.NOME,US.EMAIL,TIP.NOME AS 'Privilegios',PAC.ENDERECO , PAC.CPF, PAC.RG , PAC.TELEFONE , PAC.DATA_NASCIMENTO
FROM Paciente AS PAC
INNER JOIN Usuario AS US ON MED.ID_USUARIO = US.ID
INNER JOIN Tipo_Usuario AS TIP ON US.ID_TIPO_USUARIO = TIP.ID;