--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DO MEDICO ---
CREATE VIEW VerMedicos 
AS 
SELECT MED.ID, MED.NOME,US.EMAIL ,TIP.NOME AS 'PRIVILEGIOS',MED.CRM,CLI.NOME_FANTASIA AS 'CLINICA', MED.ID_ESPECIALIDADE AS 'ESPECIALIDADE'
FROM Medico AS MED
INNER JOIN Usuario			AS US	ON MED.ID_USUARIO		= US.ID
INNER JOIN Tipo_Usuario		AS TIP	ON US.ID_TIPO_USUARIO	= TIP.ID
INNER JOIN Clinica			AS CLI	ON MED.ID_CLINICA		= CLI.ID
INNER JOIN Especialidade	AS ESP	ON MED.ID_ESPECIALIDADE = MED.ID;

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DO PACIENTE ---
CREATE VIEW VerPacientes
AS
SELECT PAC.ID,PAC.NOME,US.EMAIL,TIP.NOME AS 'PRIVILEGIOS', PAC.CPF, PAC.RG , PAC.TELEFONE , PAC.DATA_NASCIMENTO AS 'DATA DE NASCIMENTO'
FROM Paciente AS PAC
INNER JOIN Usuario		AS US	ON PAC.ID_USUARIO		= US.ID
INNER JOIN Tipo_Usuario AS TIP	ON US.ID_TIPO_USUARIO	= TIP.ID;

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DA CLINICA ---
CREATE VIEW VerClinicas
AS
SELECT ID, NOME_FANTASIA ,ENDERECO , NUMERO , CEP
FROM Clinica;

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DA CONSULTA ---
CREATE VIEW VerConsultas
AS
SELECT CON.ID, MED.NOME AS 'DOUTOR' , PAC.NOME AS 'PACIENTE' , CLI.NOME_FANTASIA AS 'CLINICA' , CLI.ENDERECO ,  ESP.NOME AS 'ESPECIALIDADE' , CON.DATA_CONSULTA 'DATA', CON.DESCRICAO
FROM Consulta AS CON
INNER JOIN VerMedicos		AS MED ON CON.ID_MEDICO		= MED.ID
INNER JOIN Especialidade	AS ESP ON MED.ESPECIALIDADE = ESP.ID
INNER JOIN VerPacientes		AS PAC ON CON.ID_PACIENTE	= PAC.ID
INNER JOIN VerClinicas		AS CLI ON MED.CLINICA		= CLI.ID;

