--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DO MEDICO ---
CREATE VIEW VerMedicos 
AS 
SELECT MED.ID, MED.NOME,US.EMAIL ,TIP.NOME AS 'TIPO DE USUARIO',MED.CRM,CLI.NOME_FANTASIA AS 'CLINICA', ESP.NOME AS 'ESPECIALIDADE'
FROM Medico AS MED
LEFT JOIN Usuario			AS US	ON MED.ID_USUARIO		= US.ID
LEFT JOIN Tipo_Usuario		AS TIP	ON US.ID_TIPO_USUARIO	= TIP.ID
LEFT JOIN Clinica			AS CLI	ON MED.ID_CLINICA		= CLI.ID
LEFT JOIN Especialidade		AS ESP	ON MED.ID_ESPECIALIDADE = ESP.ID;
GO

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DO PACIENTE ---
CREATE VIEW VerPacientes
AS
SELECT PAC.ID,PAC.NOME,US.EMAIL,TIP.NOME AS 'TIPO DE USUARIO', PAC.CPF, PAC.RG , PAC.TELEFONE , PAC.DATA_NASCIMENTO AS 'DATA DE NASCIMENTO', YEAR(GETDATE()) - YEAR(PAC.DATA_NASCIMENTO)  AS 'IDADE'
FROM Paciente AS PAC
LEFT JOIN Usuario		AS US	ON PAC.ID_USUARIO		= US.ID
LEFT JOIN Tipo_Usuario AS TIP	ON US.ID_TIPO_USUARIO	= TIP.ID;
GO

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DA CLINICA ---
CREATE VIEW VerClinicas
AS
SELECT ID, NOME_FANTASIA ,ENDERECO , NUMERO , CEP
FROM Clinica;
GO

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DA CONSULTA ---
CREATE VIEW VerConsultas
AS
SELECT CON.ID, MED.NOME AS 'DOUTOR' , PAC.NOME AS 'PACIENTE' , MED.CLINICA AS 'CLINICA' , CLI.ENDERECO ,  MED.ESPECIALIDADE AS 'ESPECIALIDADE' , CON.DATA_CONSULTA 'DATA', CON.DESCRICAO
FROM Consulta AS CON
LEFT JOIN VerMedicos		AS MED ON CON.ID_MEDICO		= MED.ID
LEFT JOIN VerPacientes		AS PAC ON CON.ID_PACIENTE	= PAC.ID
LEFT JOIN Clinica			AS CLI ON MED.CLINICA		= CLI.NOME_FANTASIA;
GO

--- VIEW QUE RETORNA TODAS AS INFORMAÇÕES DO USUARIO ---
CREATE VIEW VerUsuarios
AS
SELECT US.EMAIL,US.SENHA,TIP.NOME AS 'TIPO DE USUARIO'
FROM Usuario AS US  
LEFT JOIN Tipo_Usuario AS TIP ON TIP.ID = US.ID_TIPO_USUARIO
WHERE US.ID_TIPO_USUARIO != 1;
GO

CREATE FUNCTION CalcularIdade (@ANO AS INT)
RETURNS INT 
AS
BEGIN
RETURN YEAR(GETDATE()) - @ANO;
END